[workspace]
members = [
    "node",
    "pallets/template",
    "pallets/hello",
    "pallets/flipper",
    "pallets/counter",
    "pallets/vault",
    "pallets/voting",
    "runtime",
]
[profile.release]
panic = "unwind"
